services:
  - type: web
    name: air-quality-insight
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    runtime: python
    region: oregon

    envVars:
      - key: FLASK_ENV
        value: production
